services:
  damastes:
    image: damastes:latest
    stdin_open: true           # docker run -i
    tty: true                  # docker run -t
    container_name: damastes   # Single container allowed.
    volumes:
      - type: bind
        source: $HOME
        target: /enjoy
      - type: bind
        source: /run/media
        target: /run/media
        bind:
          propagation: shared  # USB sticks provided for.
    working_dir: /enjoy
