services:
  damastes:
    image: damastes:latest
    volumes:
      - type: bind
        source: $HOME
        target: /enjoy
      - type: bind
        source: /run/media
        target: /run/media
        bind:
          propagation: shared
    working_dir: /enjoy
