[project]
name = "damastes"
version = "0.9.5"
description = "Damastes a.k.a. Procrustes, audiobook builder: copy and edit on the fly"
authors = [{ name = "Tyrn", email = "a@b.com" }]
readme = "README.rst"
requires-python = ">=3.13,<4.0"
dependencies = [
    "mutagen (>=1.47.0,<2.0.0)",
    "yaspin (>=3.1.0,<4.0.0)",
    "click (>=8.2.1,<9.0.0)",
]

[tool.poetry]
packages = [{ include = "damastes", from = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=8.4.2,<9.0.0)",
    "mypy (>=1.18.1,<2.0.0)",
    "pytest-mock (>=3.15.0,<4.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "black (>=25.1.0,<26.0.0)",
    "pre-commit (>=4.3.0,<5.0.0)",
    "pylint (>=3.3.8,<4.0.0)",
    "pyright (>=1.1.405,<2.0.0)",
    "virtualenvwrapper (>=6.1.1,<7.0.0)",
]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
