[tool.poetry]
name = "damastes"
version = "0.9.1"
description = ""
authors = ["Tyrn <a@b.com>"]

[tool.poetry.dependencies]
python = "^3.9"
mutagen = "^1.44"
yaspin = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.9"
mypy = "^0.790"
black = "^21.7b0"

[tool.poetry.scripts]
damastes = "damastes.main:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

