[tool.poetry]
name = "py-procr"
version = "0.1.0"
description = ""
authors = ["Tyrn <a@b.com>"]

[tool.poetry.dependencies]
python = "^3.8"
mutagen = "^1.44"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
pcp = "py_procr.pcp:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
